version: 0.0
os: linux

files:
  - source: .
    destination: /home/ec2-user/resume_songseungju
    overwrite: yes

permissions:
  - object: /home/ec2-user/resume_songseungju
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root
